### ISSUE TITLE
Cannot read property 'emit' of undefined

### ISSUE THREAD

**Issue by longfeiling** [mcuking/offline-package-webpack-plugin#1]
webpack 版本为3.6.0 使用这个插件报以下错误

TypeError: Cannot read property 'emit' of undefined
    at OfflinePackagePlugin.apply (/Users/vue-acts/2020/06/cloundTravel/node_modules/offline-package-webpack-plugin/lib/plugin.js:41:20)
    at Compiler.apply (/Users/vue-acts/2020/06/cloundTravel/node_modules/tapable/lib/Tapable.js:375:16)
    at webpack (/Users/vue-acts/2020/06/cloundTravel/node_modules/webpack/lib/webpack.js:33:19)
    at Object.<anonymous> 
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)

**Comment by mcuking** [comment]
应该是因为新旧版本 webpack 的 hooks 注册方式不同导致的。

不过十分抱歉，这个插件只支持在 webpack 4+ 使用，没有兼容 webpack 3.x 的打算。

建议项目升级到 webpack 4+ 或者可以再开发一个兼容 webpack 3.x 版本的插件。
